version: 2
jobs:
  lint:
    docker:
      - image: ruby:2.5-stretch
    steps:
      - checkout
      - run:
          name: Lint
          command: bin/lint.sh

workflows:
  version: 2
  lint:
    jobs:
      - lint